[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/test-hot-tost-csp/browser"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"

# CSP headers are now set dynamically in server.ts with nonces
# Keeping only the other security headers for static assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"